### PR TITLE
- Added `tmr_print()`

### PR DESCRIPTION
**Pull request by nadinehussein**
Closes very old issues #4 and #6

Functions organized in reference pkgdown documentation.

Need better tests for tmr_print().

### CODE REVIEW

**Review by joethorley — CHANGES_REQUESTED** [review]
print function must print internally and then return invisible copy of object

```
fun2 <- function(x) {print(x); invisible(x);}
```

see https://adv-r.hadley.nz/s3.html?q=print#nextmethod

and same thing for ```if (!tmr_is_started(x)) {
    return(x)
  }```

**Review by joethorley — CHANGES_REQUESTED** [review]
Also need test that returns invisible copy of x and also that produces output which should be tested using https://testthat.r-lib.org/reference/expect_snapshot.html

for invisible copy something like

```
expect_identical(print_tmr(x), x)
```

```
testthat::expect_invisible(print_tmr(x))
```

**Comment by joethorley** [comment]
also use `Sys.sleep(0.001)` sparingly to test more than a certain number

**Review by joethorley — CHANGES_REQUESTED** [review]
Getting there!

Isn't this line of code altering x so the returned value is not the same as that which was passed?

```
x <- tmr_ceiling(tmr_elapsed(x))
```

**Comment by nadinehussein** [comment]
> Getting there!
> 
> Isn't this line of code altering x so the returned value is not the same as that which was passed?
> 
> ```
> x <- tmr_ceiling(tmr_elapsed(x))
> ```

I suppose, but without rounding it up the time passed is always a second short. 

```
> x <- tmr_start(tmr_timer())
> tmr_print(x)
[1] "18:55:24 (+00:00:01 => 18:55:26)"
```

I changed it to save x as the initial unrounded time.

**Comment by joethorley** [comment]
Right - that's what the ceiling code was doing. Can you revert to the original code - then I think its good to go.

**Pull request merged**
